name: Build Vue
on: [push]
jobs:
  build_vue:
    if: github.repository_owner == 'RPCS4'
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'RPCS4'
        reponame: 'rpcs4.github.io'
        token: ${{ secrets.GITHUB_TOKEN }}
